dist: trusty
sudo: false

branches:
  only:
    - master
    - setup-build

language: node_js
node_js:
  - "8.9.4"

before_script:
  - npm install -g ionic cordova

script: 
  - ionic cordova build browser --prod