dist: trusty
sudo: false

branches:
  except:
    - gh-pages

language: node_js
node_js:
  - "8.9.4"

before_script:
  - npm install -g ionic

script: 
  - npm run build-prod

deploy:
  skip_cleanup: true
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: www/
  on:
    branch: master